version: '3.8'

services:

  # sqlite-service:
  #   image: nouchka/sqlite3
  #   container_name: sqlite
  #   volumes:
  #     - ./data:/data

  #     version: '3.8'

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_db     
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  python:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: python
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local